### ISSUE TITLE
Mimetype prediction

### ISSUE THREAD

**Issue by jhart99** [aseigneurin/spark-ui-proxy#12]
spark-ui-proxy returns incorrect mime types for stylesheets.  If the proxy is running behind a loadbalancer that upgrades the connections to https, Chrome and Firefox refuse to process the css leading to a broken looking UI.

When directly accessing the stylesheets from the spark master you get:
`Content-Type: text/css`
When accessing stylesheets through the proxy it returns:
`Content-Type: text/plain; charset=utf-8`

I've sent a Pull request which just adds a few lines to predict mimetypes which should resolve this.  Otherwise there might be a way to just forward the Content-Type through the proxy.

**Comment by aseigneurin** [comment]
Thanks for reporting that, and sorry for the delay. I just looked at this issue and modified the script to capture the content type from the original response and funnel it back in the response of the proxy. This should work as expected. Let me know if you see any problem.
