### ISSUE TITLE
The proxy only returns OK

### ISSUE THREAD

**Issue by mcapuccini** [aseigneurin/spark-ui-proxy#18]
Hi! I have followed the instructions in the README, and deployed the UI proxy with Docker. However if I try to open http://localhost:9999 I just get an `OK` message. Any idea on what I may be doing wrong?

**Comment by aseigneurin** [comment]
I would suspect the proxy is hitting the wrong URL.

Did you check the logs? They should tell you what URL is being called, and if you double check that URL, you might find what's wrong.

**Comment by mcapuccini** [comment]
Thanks for the quick reply. This is the log I get out of the Docker container:
```
Starting server on http://0.0.0.0:9999
127.0.0.1 - - [14/Jun/2018 08:45:37] "GET / HTTP/1.1" 200 -
```

This is how I started the Docker container:
```
docker build -t spark-ui-proxy https://github.com/aseigneurin/spark-ui-proxy.git
docker run -d --net host spark-ui-proxy localhost:8080 9999 
```

I curled localhost:8080 and I get the Spark interface. Any idea?

**Comment by mcapuccini** [comment]
I made more tests, and weirdly enough, if I add a random path to the URL I am curling I get the Spark homepage back. 

`http://localhost:9999/yadayada` and`http://localhost:9999/blabla` return both the Spark home page.  `http://localhost:9999` returns OK (I'd like this to return the Spark master homepage).

Any idea?

**Comment by mcapuccini** [comment]
I have found the problem and sent a PR to fix it: https://github.com/aseigneurin/spark-ui-proxy/pull/19.

**Comment by aseigneurin** [comment]
Thanks for the investigation and the PR! I merged your PR.
