### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by sananth12** [aseigneurin/spark-ui-proxy#7]
I get the following error message when I run the script:

<img width="470" alt="screen shot 2017-04-25 at 1 08 33 pm" src="https://cloud.githubusercontent.com/assets/3823550/25398002/63e42e5a-29b8-11e7-8bc5-4113712fca85.png">

(NOTE: I don't have root access on the server.)

**Comment by aseigneurin** [comment]
You're not giving much details... Maybe we should start with that...

How are you running the program? When does this happen? Do you have more logs?
